export const HAIRCUT_OPTIONS = [
  'No change',
  'Random',
  'Straight',
  'Wavy',
  'Curly',
  'Bob',
  'Pixie Cut',
  'Layered',
  'Messy Bun',
  'High Ponytail',
  'Low Ponytail',
  'Braided Ponytail',
  'French Braid',
  'Dutch Braid',
  'Fishtail Braid',
  'Space Buns',
  'Top Knot',
  'Undercut',
  'Mohawk',
  'Crew Cut',
  'Faux Hawk',
  'Slicked Back',
  'Side-Parted',
  'Center-Parted',
  'Blunt Bangs',
  'Side-Swept Bangs',
  'Shag',
  'Lob',
  'Angled Bob',
  'A-Line Bob',
  'Asymmetrical Bob',
  'Graduated Bob',
  'Inverted Bob',
  'Layered Shag',
  'Choppy Layers',
  'Razor Cut',
  'Perm',
  'Ombré',
  'Straightened',
  'Soft Waves',
  'Glamorous Waves',
  'Hollywood Waves',
  'Finger Waves',
  'Tousled',
  'Feathered',
  'Pageboy',
  'Pigtails',
  'Pin Curls',
  'Rollerset',
  'Twist Out',
  'Bantu Knots',
  'Dreadlocks',
  'Cornrows',
  'Box Braids',
  'Crochet Braids',
  'Double Dutch Braids',
  'French Fishtail Braid',
  'Waterfall Braid',
  'Rope Braid',
  'Heart Braid',
  'Halo Braid',
  'Crown Braid',
  'Braided Crown',
  'Bubble Braid',
  'Bubble Ponytail',
  'Ballerina Braids',
  'Milkmaid Braids',
  'Bohemian Braids',
  'Flat Twist',
  'Crown Twist',
  'Twisted Bun',
  'Twisted Half-Updo',
  'Twist and Pin Updo',
  'Chignon',
  'Simple Chignon',
  'Messy Chignon',
  'French Twist',
  'French Twist Updo',
  'French Roll',
  'Updo',
  'Messy Updo',
  'Knotted Updo',
  'Ballerina Bun',
  'Banana Clip Updo',
  'Beehive',
  'Bouffant',
  'Hair Bow',
  'Half-Up Top Knot',
  'Half-Up, Half-Down',
  'Messy Bun with a Headband',
  'Messy Bun with a Scarf',
  'Messy Fishtail Braid',
  'Sideswept Pixie',
  'Mohawk Fade',
  'Zig-Zag Part',
  'Victory Rolls'
] as const

export const HAIR_COLOR_OPTIONS = [
  'No change',
  'Random',
  'Blonde',
  'Brunette',
  'Black',
  'Dark Brown',
  'Medium Brown',
  'Light Brown',
  'Chestnut',
  'Auburn',
  'Copper',
  'Red',
  'Strawberry Blonde',
  'Platinum Blonde',
  'Silver',
  'White',
  'Blue',
  'Purple',
  'Pink',
  'Green',
  'Blue-Black',
  'Golden Blonde',
  'Honey Blonde',
  'Caramel',
  'Mahogany',
  'Burgundy',
  'Jet Black',
  'Ash Brown',
  'Ash Blonde',
  'Titanium',
  'Rose Gold'
] as const
