// <auto-generated />
using System;
using AiStyleApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AiStyleApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260802023927_AddAutomaticPrimaryRecommendation")]
    partial class AddAutomaticPrimaryRecommendation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiStyleApp.Data.Entities.FaceAnalysisJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("AnalysisConfidence")
                        .HasColumnType("double precision")
                        .HasColumnName("analysis_confidence");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("FeatureVectorJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("feature_vector_json");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gender");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<string>("PreferencesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("preferences_json");

                    b.Property<Guid?>("PrimaryGenerationJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_generation_job_id");

                    b.Property<string>("PrimaryStyleId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("primary_style_id");

                    b.Property<Guid?>("PrimaryStyleItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_style_item_id");

                    b.Property<string>("QualityFailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("quality_failure_code");

                    b.Property<string>("QualityMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("quality_message");

                    b.Property<bool?>("QualityPassed")
                        .HasColumnType("boolean")
                        .HasColumnName("quality_passed");

                    b.Property<string>("RecommendationsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("recommendations_json");

                    b.Property<DateTimeOffset?>("SelectedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("selected_at_utc");

                    b.Property<Guid?>("SelectedGenerationJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("selected_generation_job_id");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryGenerationJobId")
                        .HasDatabaseName("ix_face_analysis_jobs_primary_generation_job_id");

                    b.HasIndex("PrimaryStyleItemId")
                        .HasDatabaseName("ix_face_analysis_jobs_primary_style_item_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_face_analysis_jobs_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_face_analysis_jobs_user_id");

                    b.ToTable("face_analysis_jobs");
                });

            modelBuilder.Entity("AiStyleApp.Data.Entities.RecommendationFeedbackEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_job_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FeedbackTagsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("feedback_tags_json");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("SelectedStyleId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("selected_style_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("AnalysisJobId")
                        .HasDatabaseName("ix_recommendation_feedback_analysis_job_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_recommendation_feedback_user_id");

                    b.ToTable("recommendation_feedback");
                });

            modelBuilder.Entity("AiStyleApp.Data.Entities.StyleItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsResultPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_result_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("prompt");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_style_items_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_style_items_user_id");

                    b.ToTable("style_items");
                });

            modelBuilder.Entity("AiStyleApp.Data.Entities.StyleJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("BeardColor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("beard_color");

                    b.Property<string>("BeardStyle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("beard_style");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("current_stage");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<string>("ExternalPredictionId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_prediction_id");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("gender");

                    b.Property<string>("HairColor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("hair_color");

                    b.Property<string>("Haircut")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("haircut");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<string>("IntermediateImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("intermediate_image_url");

                    b.Property<bool>("IsBeardStagePending")
                        .HasColumnType("boolean")
                        .HasColumnName("is_beard_stage_pending");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("job_type");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("PipelineMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pipeline_mode");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("prompt");

                    b.Property<string>("ResultImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("result_image_url");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("StyleItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("style_item_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExternalPredictionId")
                        .HasDatabaseName("ix_style_jobs_external_prediction_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_style_jobs_status");

                    b.HasIndex("StyleItemId")
                        .HasDatabaseName("ix_style_jobs_style_item_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_style_jobs_user_id");

                    b.ToTable("style_jobs");
                });

            modelBuilder.Entity("AiStyleApp.Data.Entities.FaceAnalysisJobEntity", b =>
                {
                    b.HasOne("AiStyleApp.Data.Entities.StyleJobEntity", null)
                        .WithMany()
                        .HasForeignKey("PrimaryGenerationJobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AiStyleApp.Data.Entities.StyleItemEntity", null)
                        .WithMany()
                        .HasForeignKey("PrimaryStyleItemId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("AiStyleApp.Data.Entities.RecommendationFeedbackEntity", b =>
                {
                    b.HasOne("AiStyleApp.Data.Entities.FaceAnalysisJobEntity", "AnalysisJob")
                        .WithMany("Feedback")
                        .HasForeignKey("AnalysisJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnalysisJob");
                });

            modelBuilder.Entity("AiStyleApp.Data.Entities.StyleJobEntity", b =>
                {
                    b.HasOne("AiStyleApp.Data.Entities.StyleItemEntity", "StyleItem")
                        .WithMany("Jobs")
                        .HasForeignKey("StyleItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StyleItem");
                });

            modelBuilder.Entity("AiStyleApp.Data.Entities.FaceAnalysisJobEntity", b =>
                {
                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("AiStyleApp.Data.Entities.StyleItemEntity", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
